### PR TITLE
Fix SBOM generation

### PR DESCRIPTION
**Pull request by bschimke95**
The folder structure of the CoreDNS rock has changed. This hardcoded version is a temporary fix to make the CI happy again.
A refactoring of the SBOM generation is done as follow-up work.

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Do you want the sbom tarball in the PR?

**Comment by bschimke95** [comment]
Nope - thanks for the catch

**Review by eaudetcobello — APPROVED** [review]
LGTM, please make sure we have a card for the follow-up work

**Comment by bschimke95** [comment]
We do have.

**Pull request merged**
