### PR TITLE
remove --output-format from k8s get-join-token

### PR DESCRIPTION
**Pull request by neoaggelos**
### Summary

`k8s get-join-token` simply prints the token in stdout

### CODE REVIEW

**Review by bschimke95 — APPROVED** [review]
LGTM

**Comment by addyess** [comment]
@bschimke95 and @neoaggelos 
is there a docs changed necessary here

**Comment by bschimke95** [comment]
Yes, there is already  an update of the docs in the diff.
docs/src/_parts/commands/k8s_get-join-token.md

**Comment by neoaggelos** [comment]
And I didn't see any changes needed for the tutorial https://documentation.ubuntu.com/canonical-kubernetes/latest/tutorial/add-remove-nodes/#bootstrap-your-control-plane-node

**Comment by addyess** [comment]
> Yes, there is already an update of the docs in the diff. docs/src/_parts/commands/k8s_get-join-token.md

oh awesome.  so sorry i missed that

**Pull request merged**
